insert into public.pilot_requests (
  tenant_id,
  workspace_id,
  name,
  email,
  organization,
  document_count_range,
  document_type,
  primary_domain,
  main_problem,
  success_criteria,
  privacy_level,
  pilot_timeline,
  notes,
  qualification_score,
  qualification_status,
  review_status,
  priority,
  next_action,
  review_owner,
  review_notes
) values
(
  'demo-tenant',
  'demo-workspace',
  'Demo Client',
  'client@example.com',
  'Example Organization',
  '50–200 documents',
  'PDF reports and technical manuals',
  'technical documentation',
  'We need evidence-backed search across technical PDFs and internal reports.',
  'Users should find answers faster and verify source documents.',
  'internal business documents',
  '30 days',
  'Start with a limited controlled workspace.',
  100,
  'green',
  'approved_for_pilot',
  'high',
  'Schedule pilot review call',
  'AndyAI operator',
  'Clear document scope, strong evidence-traceability need, and measurable success criteria.'
)
on conflict do nothing;
