export const visualAtlasLegends = [
  {
    id: "kf-architecture",
    title: "Knowledge Factory Architecture",
    image: "/canon-visuals/andyai_knowledge_factory_architecture_diagram.png",
    category: "Core Knowledge Factory",
    oneLineMeaning: "The full architecture of AndyAI Knowledge Factory.",
    whatThisShows: "How documents move through ingestion, retrieval, evidence, wiki synthesis, graph structure, human approval, and visual/product layers.",
    whyItMatters: "It proves that the system is not just RAG; it is a governed knowledge factory.",
    keyElements: ["document sources", "ingestion layer", "retrieval layer", "LLM Wiki", "Knowledge Graph", "Evidence Pack", "Human Approval", "Visual Atlas"],
    processFlow: ["Documents enter the factory", "Content is parsed and chunked", "Retrieval finds relevant fragments", "Evidence and synthesis layers structure the result", "Humans approve durable knowledge"],
    practicalTakeaway: "Architecture must show where trust, structure, and approval enter the system.",
    andyaiAngle: "RAG finds fragments; Knowledge Factory creates governed knowledge."
  },
  {
    id: "massive-ingestion",
    title: "Massive Document Ingestion Pipeline",
    image: "/canon-visuals/massive_document_ingestion_pipeline_infographic.png",
    category: "Core Knowledge Factory",
    oneLineMeaning: "The large-scale PDF intake path.",
    whatThisShows: "How 100–200 PDFs with around 1,000 pages each become clean, chunked, metadata-rich ingestion assets.",
    whyItMatters: "Bad ingestion creates bad retrieval; disciplined ingestion creates reliable knowledge work.",
    keyElements: ["PDF intake", "OCR / text extraction", "chunking", "metadata extraction", "document registry", "retrieval-ready storage"],
    processFlow: ["Documents enter intake", "Text is extracted or OCR processed", "Content is normalized and chunked", "Metadata and source references are attached", "Chunks become retrieval-ready"],
    practicalTakeaway: "Retrieval quality begins before retrieval.",
    andyaiAngle: "Document chaos must become an ordered evidence stream."
  },
  {
    id: "new-rag-paradigm",
    title: "The New RAG Paradigm",
    image: "/canon-visuals/the_new_rag_paradigm_flowchart.png",
    category: "Core Knowledge Factory",
    oneLineMeaning: "RAG is only the retrieval layer, not the whole system.",
    whatThisShows: "The transition from classic RAG into Knowledge Factory: retrieval → evidence → wiki → graph → approval.",
    whyItMatters: "It positions AndyAI Knowledge Factory above commodity RAG systems.",
    keyElements: ["retrieval", "evidence pack", "LLM Wiki", "Knowledge Graph", "approval", "canonical knowledge"],
    processFlow: ["RAG retrieves fragments", "Evidence packs preserve source trace", "Wiki and graph layers structure knowledge", "Human approval turns proposals into durable knowledge"],
    practicalTakeaway: "RAG answers questions; Knowledge Factory builds reusable knowledge assets.",
    andyaiAngle: "RAG is the intake machine; Knowledge Factory is the governed knowledge system."
  },
  {
    id: "workflows-control-tower",
    title: "Knowledge Workflows & Production Control Tower",
    image: "/canon-visuals/knowledge_workflows_and_production_control_tower.png",
    category: "Runtime and Deployment",
    oneLineMeaning: "How knowledge work becomes controlled production work.",
    whatThisShows: "Workflow execution, gates, production checks, deployment readiness, rollback thinking, and proof bundles.",
    whyItMatters: "A knowledge system must be operated, not merely demonstrated.",
    keyElements: ["workflows", "production gates", "control tower", "verification", "release proof", "rollback path"],
    processFlow: ["A workflow is started", "Gates check readiness", "Outputs are verified", "Evidence is bundled", "Production decisions are controlled"],
    practicalTakeaway: "Serious AI products need operational discipline.",
    andyaiAngle: "The factory works only when the control tower sees the whole runway."
  },
  {
    id: "knowledge-governance",
    title: "Knowledge Governance Workflow",
    image: "/canon-visuals/the_andyai_knowledge_governance_workflow.png",
    category: "Governance and Trust",
    oneLineMeaning: "How claims become governed knowledge.",
    whatThisShows: "The path from retrieved fragments to proposed claims, evidence packs, review, approval, and export.",
    whyItMatters: "The system must distinguish between generated proposals and approved knowledge.",
    keyElements: ["retrieved fragments", "proposed claims", "evidence pack", "review queue", "approval record", "export bundle"],
    processFlow: ["Retrieval finds supporting fragments", "The system proposes claims", "Evidence is attached", "A human reviews", "Approved outputs become reusable knowledge"],
    practicalTakeaway: "No approval, no trusted external output.",
    andyaiAngle: "Approval state is part of meaning."
  },
  {
    id: "system-stack",
    title: "Knowledge Factory System Stack",
    image: "/canon-visuals/andyai_knowledge_factory_system_stack.png",
    category: "Core Knowledge Factory",
    oneLineMeaning: "The layered technical structure of the product.",
    whatThisShows: "How UI, runtime, data, retrieval, AI, governance, and DevOps layers fit together.",
    whyItMatters: "It helps builders and partners understand where each system responsibility lives.",
    keyElements: ["product surface", "API / runtime", "database", "vector search", "AI synthesis", "governance", "DevOps"],
    processFlow: ["Users interact through the product surface", "Runtime services coordinate work", "Data and retrieval layers provide context", "AI synthesis proposes outputs", "Governance controls release and reuse"],
    practicalTakeaway: "A professional AI product is a stack, not a prompt.",
    andyaiAngle: "The stack must make trust visible."
  },
  {
    id: "system-map",
    title: "Knowledge Factory System Map",
    image: "/canon-visuals/andyai_knowledge_factory_system_map.png",
    category: "Core Knowledge Factory",
    oneLineMeaning: "The whole system as one connected map.",
    whatThisShows: "How all major product and knowledge layers connect into a single factory.",
    whyItMatters: "It gives stakeholders a complete mental model.",
    keyElements: ["documents", "ingestion", "retrieval", "wiki", "graph", "evidence", "approval", "atlas", "exports"],
    processFlow: ["Source material enters", "Knowledge layers process and structure it", "Trust layers verify it", "Product layers make it understandable and usable"],
    practicalTakeaway: "The value is in the connections between layers.",
    andyaiAngle: "Knowledge becomes powerful when it becomes connected."
  },
  {
    id: "product-surface-map",
    title: "Product Surface & System Map",
    image: "/canon-visuals/andyai_product_surface_and_system_map.png",
    category: "Runtime and Deployment",
    oneLineMeaning: "How public pages connect to internal modules.",
    whatThisShows: "The relationship between product pages, operator tools, knowledge layers, governance, and infrastructure.",
    whyItMatters: "It turns the repo into a product surface, not just backend code.",
    keyElements: ["home", "architecture", "playground", "docs", "pricing", "waitlist", "atlas", "control tower", "runtime stack"],
    processFlow: ["Visitors enter through public pages", "Operators use internal tools", "Backend services handle retrieval and governance", "Product pages explain the system"],
    practicalTakeaway: "Product explanation and product operation must meet.",
    andyaiAngle: "A serious product shows both interface and machinery."
  },
  {
    id: "human-approval-loop",
    title: "Operator Review & Approval Loop",
    image: "/canon-visuals/extended/human_in_the_loop_knowledge_approval_process.png",
    category: "Governance and Trust",
    oneLineMeaning: "The human decision loop for durable knowledge.",
    whatThisShows: "How agentic output moves into review, evidence checking, approval, rejection, revision, lock, export, and reuse.",
    whyItMatters: "It protects the product from unreviewed AI output.",
    keyElements: ["agentic compilation", "review queue", "human reviewer", "approve / reject / needs revision", "evidence check", "locked knowledge"],
    processFlow: ["The system proposes knowledge", "The item enters the review queue", "A human checks evidence", "The decision is recorded", "Approved knowledge can be reused"],
    practicalTakeaway: "Humans are not decorative; they are the governance layer.",
    andyaiAngle: "Agent output is a proposal until human approval."
  },
  {
    id: "supabase-runtime",
    title: "Supabase Runtime & Multi-Tenant Model",
    image: "/canon-visuals/extended/supabase_runtime_and_multi_tenant_model_overview.png",
    category: "Runtime and Deployment",
    oneLineMeaning: "The runtime model for users, tenants, permissions, and usage.",
    whatThisShows: "How auth, workspaces, RLS, documents, chunks, evidence packs, subscriptions, and usage events connect.",
    whyItMatters: "Multi-tenant knowledge products require isolation and traceability.",
    keyElements: ["Supabase Auth", "tenants / workspaces", "RLS", "documents", "chunks", "evidence packs", "usage events", "quota counters"],
    processFlow: ["User authenticates", "Tenant/workspace scope is applied", "Runtime reads and writes governed data", "Usage and quotas are tracked", "RLS protects tenant boundaries"],
    practicalTakeaway: "SaaS trust begins with correct data boundaries.",
    andyaiAngle: "Tenant isolation is a knowledge safety feature."
  },
  {
    id: "vercel-release",
    title: "Vercel Deploy & Release Pipeline",
    image: "/canon-visuals/extended/vercel_deploy_and_release_pipeline_diagram.png",
    category: "Runtime and Deployment",
    oneLineMeaning: "The release path from GitHub to production.",
    whatThisShows: "GitHub, CI verify, version tags, Vercel build, preview deploy, production deploy, monitoring, and rollback.",
    whyItMatters: "A product must have a safe release path.",
    keyElements: ["GitHub repo", "CI verify", "tag", "preview deployment", "production deployment", "monitoring", "rollback"],
    processFlow: ["Code is committed", "Verification runs", "A version is tagged", "Vercel builds and previews", "Production deploy is gated", "Rollback remains available"],
    practicalTakeaway: "Deploy is not a button; deploy is a controlled path.",
    andyaiAngle: "Check. Gate. Deploy. Verify. Prove. Rollback if needed."
  },
  {
    id: "evidence-lifecycle",
    title: "Evidence Pack Lifecycle",
    image: "/canon-visuals/extended/evidence_pack_lifecycle_infographic_flowchart.png",
    category: "Governance and Trust",
    oneLineMeaning: "How source proof becomes reusable evidence.",
    whatThisShows: "The lifecycle from raw source to parsed content, chunks, claims, citation anchors, review, signed/approved evidence, exports, and audit trail.",
    whyItMatters: "Evidence must remain traceable across the whole product.",
    keyElements: ["raw source", "parsed content", "chunk", "claim", "citation anchor", "evidence pack", "human review", "signed evidence", "audit trail"],
    processFlow: ["Source material is parsed", "Chunks and claims are extracted", "Citation anchors are created", "Evidence packs are assembled", "Humans approve", "Approved evidence is reused and audited"],
    practicalTakeaway: "Trust requires traceability.",
    andyaiAngle: "No evidence, no trusted answer."
  },
  {
    id: "permission-access",
    title: "Permission-Aware Access Map",
    image: "/canon-visuals/extended/permission_aware_access_map_for_andyai.png",
    category: "Governance and Trust",
    oneLineMeaning: "Who can see, review, approve, export, and manage knowledge.",
    whatThisShows: "Roles, resources, permissions, workspaces, approval paths, and least-privilege boundaries.",
    whyItMatters: "Not every user should touch every piece of knowledge.",
    keyElements: ["admin", "operator", "analyst", "viewer", "public", "documents", "graph", "evidence packs", "exports"],
    processFlow: ["A user enters with a role", "Workspace scope is applied", "Permissions filter what can be viewed or changed", "Approval and export actions follow stricter rules"],
    practicalTakeaway: "Access control is part of knowledge governance.",
    andyaiAngle: "Permission-aware retrieval prevents unsafe knowledge exposure."
  },
  {
    id: "super-poster",
    title: "100–200 PDFs × 1,000 Pages → Knowledge Factory",
    image: "/canon-visuals/extended/knowledge_factory_platform_architecture_diagram.png",
    category: "Core Knowledge Factory",
    oneLineMeaning: "The whole origin story in one super-poster.",
    whatThisShows: "The full journey from massive PDFs to ingestion, retrieval, wiki, graph, atlas, workflows, evidence packs, approval, product site, and exports.",
    whyItMatters: "It explains the whole product in the same frame as the original problem.",
    keyElements: ["large document intake", "parsing and OCR", "chunking and metadata", "hybrid retrieval", "evidence packs", "LLM Wiki", "Knowledge Graph", "Visual Atlas", "human approval", "exports"],
    processFlow: ["Massive document collections enter", "The factory extracts and structures content", "Retrieval finds fragments", "Evidence proves claims", "Knowledge layers organize meaning", "Humans approve", "Outputs become reusable product assets"],
    practicalTakeaway: "The original PDF problem becomes a full knowledge infrastructure product.",
    andyaiAngle: "A naive question became a sovereign Knowledge Factory."
  }
];

export const visualAtlasStoryFlow = [
  { stepId: "step-01", order: 1, title: "Massive document chaos", diagramId: "super-poster", storyRole: "origin problem", userQuestionAnswered: "What problem does this product solve?" },
  { stepId: "step-02", order: 2, title: "Disciplined ingestion", diagramId: "massive-ingestion", storyRole: "input discipline", userQuestionAnswered: "How do huge PDFs become usable?" },
  { stepId: "step-03", order: 3, title: "New RAG paradigm", diagramId: "new-rag-paradigm", storyRole: "conceptual bridge", userQuestionAnswered: "Why is this more than RAG?" },
  { stepId: "step-04", order: 4, title: "Evidence lifecycle", diagramId: "evidence-lifecycle", storyRole: "trust foundation", userQuestionAnswered: "How do we know where claims come from?" },
  { stepId: "step-05", order: 5, title: "Human approval", diagramId: "human-approval-loop", storyRole: "governance loop", userQuestionAnswered: "When does AI output become approved knowledge?" },
  { stepId: "step-06", order: 6, title: "System architecture", diagramId: "kf-architecture", storyRole: "full architecture", userQuestionAnswered: "How does the whole factory fit together?" },
  { stepId: "step-07", order: 7, title: "Runtime and deployment", diagramId: "vercel-release", storyRole: "production path", userQuestionAnswered: "How does this become a deployed product?" }
];

export const visualAtlasDemoSummary = {
  product: "AndyAI Knowledge Factory",
  site: "knowledgefactory.andyai.ai",
  version: "v16.5.0",
  totalDiagrams: 14,
  totalLegends: visualAtlasLegends.length,
  canonicalRule: "The visual atlas is not a gallery. It is the product explanation engine.",
  serbianRule: "Vizuelni atlas nije galerija. On je motor za objašnjavanje proizvoda.",
  proverb: "Slike se ne kupe metlom — slike se biraju pincetom."
};
